language: go

go:
  - 1.9.x

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs yarn
  - yarn install
  - yarn build

script:
  - go test -v $(glide novendor)
  - go build -v .

