export const APP_INIT = 'APP_INIT';
export const APP_INIT_ERROR = 'APP_INIT_ERROR';

export const REGISTERED_USERS_REQUEST = 'GET_REGISTERED_USERS_REQUEST';
export const REGISTERED_USERS_SUCCESS = 'GET_REGISTERED_USERS_SUCCESS';
export const REGISTERED_USERS_FAIL = 'GET_REGISTERED_USERS_FAIL';

export const DIALER_STATUS_REQUEST = 'DIALER_STATUS_REQUEST';
export const DIALER_STATUS_SUCCESS = 'DIALER_STATUS_SUCCESS';
export const DIALER_STATUS_FAIL = 'DIALER_STATUS_FAIL';

export const DIALER_START_REQUEST = 'DIALER_START_REQUEST';
export const DIALER_START_SUCCESS = 'DIALER_START_SUCCESS';
export const DIALER_START_FAIL = 'DIALER_START_FAIL';

export const DIALER_STOP_REQUEST = 'DIALER_STOP_REQUEST';
export const DIALER_STOP_SUCCESS = 'DIALER_STOP_SUCCESS';
export const DIALER_STOP_FAIL = 'DIALER_STOP_FAIL';

export const PAGING_CHANGE_REQUEST = 'PAGING_CHANGE_REQUEST';
export const PAGING_CHANGE_SUCCESS = 'PAGING_CHANGE_SUCCESS';
export const PAGING_CHANGE_FAIL = 'PAGING_CHANGE_FAIL';

export const SUBMIT_CHANGE_PRIORITY_REQUEST = 'SUBMIT_CHANGE_PRIORITY_REQUEST';
export const SUBMIT_CHANGE_PRIORITY_SUCCESS = 'SUBMIT_CHANGE_PRIORITY_SUCCESS';
export const SUBMIT_CHANGE_PRIORITY_FAIL = 'SUBMIT_CHANGE_PRIORITY_FAIL';

export const CALL_IN_PROGRESS_REQUEST = 'CALL_IN_PROGRESS_REQUEST';
export const CALL_IN_PROGRESS_SUCCESS = 'CALL_IN_PROGRESS_SUCCESS';
export const CALL_IN_PROGRESS_FAIL = 'CALL_IN_PROGRESS_FAIL';

export const DELETE_RECORD_REQUEST = 'DELETE_RECORD_REQUEST';
export const DELETE_RECORD_SUCCESS = 'DELETE_RECORD_SUCCESS';
export const DELETE_RECORD_FAIL = 'DELETE_RECORD_FAIL';
